NGame = { 
	START_DATE = "1936.1.1.12",
	END_DATE = "1949.1.1.1",
	MAP_SCALE_PIXEL_TO_KM = 7.114,					-- Yes, we did the math
	SAVE_VERSION = 25,								-- 1.16.0 (Countenance)
	CHECKSUM_SALT = "zwOdv5d9wm9uDSOT",				-- Data to modify generated checksum when game binaries have changed but not any content files.
	LAG_DAYS_FOR_LOWER_SPEED = 10,					-- Days of client lag for decrease of gamespeed
	LAG_DAYS_FOR_PAUSE = 25,						-- Days of client lag for pause of gamespeed.
	GAME_SPEED_SECONDS = { 2.0, 0.5, 0.2, 0.1, 0.0 }, -- game speeds for each level. Must be 5 entries with last one 0 for unbound
	MAJOR_PARTICIPANTS_FOR_MAJOR_WAR = 3,			-- Minimum number of major countries involved in a war to consider it major enough to not end the game even though the enddate has been reached.
	TRADE_ROUTE_RECALCULATE_FREQUENCY_DAYS = 30, -- Max recalculation time for all trade routes (0 means we do not recalucate prediodically trade routes)
	COMBAT_LOG_MAX_MONTHS = 12,
	MESSAGE_TIMEOUT_DAYS = 60,						-- Useful if running the handsoff game. The popup messages that doesn't require the player respond will automatically hide after some timeout.
	INFO_MESSAGE_TIMEOUT_DAYS = 3,					-- Same but for unimportant messages.
	AIR_LOG_TIMEOUT_HOURS = 24,						-- Data storring data
	EVENT_TIMEOUT_DEFAULT = 13,						-- Default days before an event times out if not scripted
	MISSION_REMOVE_FROM_INTERFACE_DEFAULT = 13,		-- Default days before a mission is removed from the interface after having failed or completed
	DECISION_ALERT_TIMEOUT_DAYS = 30,				-- Days left when player will be alerted about timing out events or decisions
	FUEL_RESOURCE = "oil",							-- resource that will give country fuel
	MAX_EFFECT_ITERATION = 1000,					-- maximum allowed iteration for loop effects
	MAX_SCRIPTED_LOC_RECURSION = 30,				-- max recursion for scripted localizations
	HANDS_OFF_START_TAG = "HAI",					-- tag for player country for -hands_off runs. use an existing tag that is less likely to affect the game
	ALERT_SFX_COOLDOWN_DAYS = 14,					-- After playing an alert sound, don't play the same sound for XXX days, even if it fires again.
	MUSIC_PLAYER_RECENTLY_PLAYED_SIZE = 10,			-- The music player keeps track of recently played music to try and avoid playing the same songs too often. This determines the max number of songs in the recently played list.
},
NGame = {--游戏基础规则
	START_DATE = "1936.1.1.12",
	END_DATE = "1949.1.1.1",
	MAP_SCALE_PIXEL_TO_KM = 7.114,					-- 是的，我们算过（地图像素与现实公里的换算比例）
	SAVE_VERSION = 25,								-- 1.16.0 版本（代号“Countenance”）
	CHECKSUM_SALT = "zwOdv5d9wm9uDSOT",				-- 当游戏二进制文件变更但内容文件未变时，用于修改校验和的数据
	LAG_DAYS_FOR_LOWER_SPEED = 10,					-- 客户端延迟多少天后会降低游戏速度
	LAG_DAYS_FOR_PAUSE = 25,						-- 客户端延迟多少天后会暂停游戏
	GAME_SPEED_SECONDS = { 2.0, 0.5, 0.2, 0.1, 0.0 }, -- 每个游戏速度等级对应的秒数（必须为5项，最后一项为0表示无限制）
	MAJOR_PARTICIPANTS_FOR_MAJOR_WAR = 3,			-- 一场战争中被视为“主要战争”所需的最少主要国家参与数（达到此数量则即使到结束日期也不会强制终止游戏）
	TRADE_ROUTE_RECALCULATE_FREQUENCY_DAYS = 30, 	-- 所有贸易路线重新计算的最大间隔天数（0表示不周期性重新计算）
	COMBAT_LOG_MAX_MONTHS = 12,						-- 战斗日志保存的最大月份数
	MESSAGE_TIMEOUT_DAYS = 60,						-- 适用于“无玩家操作”模式：无需玩家响应的弹窗消息将在超时后自动隐藏
	INFO_MESSAGE_TIMEOUT_DAYS = 3,					-- 同上，但用于不重要的消息
	AIR_LOG_TIMEOUT_HOURS = 24,						-- 空军日志数据的存储时长（小时）
	EVENT_TIMEOUT_DEFAULT = 13,						-- 事件默认超时天数（若未在脚本中指定）
	MISSION_REMOVE_FROM_INTERFACE_DEFAULT = 13,		-- 任务失败或完成后，从界面移除的默认天数
	DECISION_ALERT_TIMEOUT_DAYS = 30,				-- 事件或决策即将超时时，提前多少天提醒玩家
	FUEL_RESOURCE = "oil",							-- 能为国家提供燃料的资源类型（石油）
	MAX_EFFECT_ITERATION = 1000,					-- 循环效果的最大允许迭代次数（防崩溃）
	MAX_SCRIPTED_LOC_RECURSION = 30,				-- 脚本本地化的最大递归深度
	HANDS_OFF_START_TAG = "HAI",					-- “无玩家操作”模式下的玩家国家标签（使用对游戏影响最小的现有标签）
	ALERT_SFX_COOLDOWN_DAYS = 14,					-- 播放警报音效后，即使再次触发，也会在多少天内不再重复播放
	MUSIC_PLAYER_RECENTLY_PLAYED_SIZE = 10,			-- 音乐播放器记录最近播放歌曲的数量上限（避免重复播放）
}