NProduction = {
	MAX_EQUIPMENT_RESOURCES_NEED = 3, 	-- Max number of different strategic resources an equipment can be dependent on.
	MAX_CIV_FACTORIES_PER_LINE = 15,	-- Max number of factories that can be assigned a single production line.
	DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 10,
	FLOATING_HARBOR_MAX_NAV_FACTORIES_PER_LINE = 5,
	CONVOY_MAX_NAV_FACTORIES_PER_LINE = 15,
	CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 5,
	MAX_MIL_FACTORIES_PER_LINE = 150,
	MAX_MIL_FACTORIES_VISIBLE_FOR_MIL_EQUIPMENT_LINE = 15,
	RAILWAY_GUN_MAX_MIL_FACTORIES_PER_LINE = 5,
	RAILWAY_GUN_REPAIR_SPEED = 8.0,			-- Railway gun strength repair speed per factory
	EFFICIENCY_LOSS_PER_UNUSED_DAY = 1,		-- Daily loss of efficiency for unused factory slots ( efficiency is tracked per factory slot in the production line )
	RESOURCE_PENALTY_WARNING_CRITICAL_RATIO =  0.8, -- Switch to red progress bar if penalty is over threshold
	BASE_FACTORY_SPEED = 5, 				-- Base factory speed multiplier (how much hoi3 style IC each factory gives).
	BASE_FACTORY_SPEED_MIL = 4.50, 				-- Base factory speed multiplier (how much hoi3 style IC each factory gives).
	BASE_FACTORY_SPEED_NAV = 2.5, 				-- Base factory speed multiplier (how much hoi3 style IC each factory gives).
	BASE_FACTORY_START_EFFICIENCY_FACTOR = 10,	-- Base start efficiency for factories expressed in %.
	BASE_FACTORY_MAX_EFFICIENCY_FACTOR = 50,	-- Base max efficiency for factories expressed in %.
	BASE_FACTORY_EFFICIENCY_GAIN = 1,		-- Base efficiency factor.
	BASE_FACTORY_EFFICIENCY_BALANCE_FACTOR = 0.1, 			-- Factory efficiency balancing factor
	BASE_FACTORY_EFFICIENCY_VARIANT_CHANGE_FACTOR = 90,		-- Base factor for changing production variants in %.
	BASE_FACTORY_EFFICIENCY_PARENT_CHANGE_FACTOR = 30,		-- Base factor for changing production parent<->children in %.
	BASE_FACTORY_EFFICIENCY_FAMILY_CHANGE_FACTOR = 70,		-- Base factor for changing production with same family in %.
	BASE_FACTORY_EFFICIENCY_ARCHETYPE_CHANGE_FACTOR = 20, 	-- Base factor for changing production with same archetype in %.
	EQUIPMENT_BASE_LEND_LEASE_WEIGHT = 1.0, -- Base equipment lend lease weight
	EQUIPMENT_LEND_LEASE_WEIGHT_FACTOR = 0.01, -- Base equipment lend lease factor
	LEND_LEASE_DELIVERY_TOTAL_DAYS = 30,                    -- Nr of days between lend lease deliveries
	ANNEX_STOCKPILES_RATIO = 1.0,		-- How much stockpiled equipment will be transferred on annexation
	ANNEX_FIELD_EQUIPMENT_RATIO = 0.25,	-- How much equipment from deployed divisions will be transferred on annexation
	ANNEX_FUEL_RATIO = 0.25,	-- How much fuel will be transferred on annexation
	ANNEX_CONVOYS_RATIO = 0.15,			-- How many convoys will be transferred on annexation
	MIN_POSSIBLE_TRAINING_MANPOWER = 100000,	-- How many deployment lines minimum can be training
	MIN_FIELD_TO_TRAINING_MANPOWER_RATIO = 0.75,	-- Ratio which % of army in field can be trained
	CAPITULATE_STOCKPILES_RATIO = 0.5, -- How much equipment from deployed divisions will be transferred on capitulation
	CAPITULATE_FUEL_RATIO = 0.5, -- How much fuel will be transferred on capitulation
	INFRA_MAX_CONSTRUCTION_COST_EFFECT = 1, 		-- Building in a state with higher infrastructure will reduce the cost of shared buildings.
	PRODUCTION_RESOURCE_LACK_PENALTY = -0.05,			-- Penalty decrease while lack of resource per factory
	CIC_BANK_SPEED_BOOST_FACTOR = 0.25,                 -- The CIC bank can boost production speed with this factor (0.5 means 50 %)
	MIN_LICENSE_ACTIVE_DAYS = 30,						-- Min days for license to be active
	BASE_LICENSE_IC_COST = 1,							-- Base IC cost for lended license
	LICENSE_IC_COST_YEAR_INCREASE = 1,					-- IC cost equipment for every year of equipment after 1936
	LICENSE_EQUIPMENT_BASE_SPEED = -0.25,				-- base MIC speed modifier for licensed equipment
	LICENSE_EQUIPMENT_TECH_SPEED_PER_YEAR = -0.05,		-- MIC speed modifier for licensed equipment for each year of difference between actual and latest equipment
	LICENSE_EQUIPMENT_TECH_SPEED_MAX_YEARS = 4,			-- Maximum years for MIC speed modifier
	LICENSE_EQUIPMENT_SPEED_NOT_FACTION = -0.10,		-- MIC speed modifier for licensed equipment for not being in faction
	LICENSE_EQUIPMENT_UPGRADE_XP_FACTOR = 2.0,			-- XP cost for upgrading licensed equipment
	LICENSE_EQUIPMENT_SPEED_NO_LICENSE = -0.50,			-- Penalty for producing non licensed equipment
	CONVERSION_SPEED_BONUS = 0,							-- Modifier to the production speed when converting equipment
	EQUIPMENT_MODULE_ADD_XP_COST = 5.0,					-- XP cost for adding a new equipment module in an empty slot when creating an equipment variant.
	EQUIPMENT_MODULE_REPLACE_XP_COST = 6.0,				-- XP cost for replacing one equipment module with an unrelated module when creating an equipment variant.
	EQUIPMENT_MODULE_CONVERT_XP_COST = 3.0,				-- XP cost for converting one equipment module to a related module when creating an equipment variant.
	EQUIPMENT_MODULE_REMOVE_XP_COST = 1.0,				-- XP cost for removing an equipment module and leaving the slot empty when creating an equipment variant.
	BASE_NAVAL_EQUIPMENT_CONVERSION_IC_COST_FACTOR = 0.2,       -- Fraction of the hull industry cost which is always included in the refitting cost.
	BASE_LAND_EQUIPMENT_CONVERSION_IC_COST_FACTOR = 0.9,        -- Fraction of the chassis industry cost which is always included in the conversion cost.
	MIN_NAVAL_EQUIPMENT_CONVERSION_RESOURCE_COST_FACTOR = 0.2,	-- Minimum fraction of a naval equipment's strategic resource cost that any conversion will cost.
	MIN_LAND_EQUIPMENT_CONVERSION_RESOURCE_COST_FACTOR = 0,		-- Minimum fraction of a land equipment's strategic resource cost that any conversion will cost.
	SHIP_REFIT_MAX_PROGRESS_TO_CANCEL = 0.2,			-- Maximum refitting progress % that we still allow to cancel wihtout having to scuttle the ship.
	SHIP_REFIT_DAMAGE_TO_PROGRESS_FACTOR = 0.5,			-- When a ship is being damaged (for example port strike) while refitting, the damage is transferred to the production line progress instead. This variable is used to balance it.
	MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_VALUE = 1,		-- The minimum number of factories we have to put on consumer goods, by value.
	MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_PERCENT = 0.1,	-- The minimum number of factories we have to put on consumer goods, in percent.
	INITIAL_ALLOWED_FACTORY_RATIO_FOR_REPAIRS = 1.0,					-- max % of factories allowed on autorepairs
},

NProduction = { --生产与装备
	MAX_EQUIPMENT_RESOURCES_NEED = 3, 	-- 一种装备最多可依赖多少种不同的战略资源
	MAX_CIV_FACTORIES_PER_LINE = 15,	-- 单个生产线最多可分配的民用工厂数量
	DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 10,  -- 默认海军装备生产线最多可分配的海军工厂数量
	FLOATING_HARBOR_MAX_NAV_FACTORIES_PER_LINE = 5,  -- 浮动港口生产线最多可分配的海军工厂数量
	CONVOY_MAX_NAV_FACTORIES_PER_LINE = 15,  -- 运输船生产线最多可分配的海军工厂数量
	CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 5,  -- 主力舰生产线最多可分配的海军工厂数量
	MAX_MIL_FACTORIES_PER_LINE = 150,  -- 单个军事装备生产线最多可分配的军事工厂数量
	MAX_MIL_FACTORIES_VISIBLE_FOR_MIL_EQUIPMENT_LINE = 15,  -- 军事装备生产线的军事工厂显示上限（界面显示用）
	RAILWAY_GUN_MAX_MIL_FACTORIES_PER_LINE = 5,  -- 铁道炮生产线最多可分配的军事工厂数量
	RAILWAY_GUN_REPAIR_SPEED = 8.0,  -- 每座工厂每日修复铁道炮强度的速度
	EFFICIENCY_LOSS_PER_UNUSED_DAY = 1,  -- 工厂槽位未使用时每日损失的效率值（每个生产线的工厂槽位单独追踪）
	RESOURCE_PENALTY_WARNING_CRITICAL_RATIO = 0.8,  -- 若资源短缺惩罚超过此阈值，则进度条变为红色警告
	BASE_FACTORY_SPEED = 5,  -- 民用工厂基础产出倍率（相当于HOI3中的IC值）
	BASE_FACTORY_SPEED_MIL = 4.50,  -- 军事工厂基础产出倍率
	BASE_FACTORY_SPEED_NAV = 2.5,  -- 海军工厂基础产出倍率
	BASE_FACTORY_START_EFFICIENCY_FACTOR = 10,  -- 工厂起始效率百分比（基础值）
	BASE_FACTORY_MAX_EFFICIENCY_FACTOR = 50,  -- 工厂最大效率百分比（基础值）
	BASE_FACTORY_EFFICIENCY_GAIN = 1,  -- 工厂效率提升的基础倍率
	BASE_FACTORY_EFFICIENCY_BALANCE_FACTOR = 0.1,  -- 工厂效率平衡修正系数
	BASE_FACTORY_EFFICIENCY_VARIANT_CHANGE_FACTOR = 90,  -- 更换装备变种时的效率保留百分比（基础值）
	BASE_FACTORY_EFFICIENCY_PARENT_CHANGE_FACTOR = 30,  -- 更换装备父级/子级时的效率保留百分比
	BASE_FACTORY_EFFICIENCY_FAMILY_CHANGE_FACTOR = 70,  -- 更换同族装备时的效率保留百分比
	BASE_FACTORY_EFFICIENCY_ARCHETYPE_CHANGE_FACTOR = 20,  -- 更换同原型装备时的效率保留百分比
	EQUIPMENT_BASE_LEND_LEASE_WEIGHT = 1.0,  -- 租借装备的基础权重
	EQUIPMENT_LEND_LEASE_WEIGHT_FACTOR = 0.01,  -- 租借装备的基础倍率因子
	LEND_LEASE_DELIVERY_TOTAL_DAYS = 30,  -- 租借物资送达周期（天数）
	ANNEX_STOCKPILES_RATIO = 1.0,  -- 吞并国家时转移其库存装备的比例
	ANNEX_FIELD_EQUIPMENT_RATIO = 0.25,  -- 吞并国家时转移其部署部队装备的比例
	ANNEX_FUEL_RATIO = 0.25,  -- 吞并国家时转移其燃料的比例
	ANNEX_CONVOYS_RATIO = 0.15,  -- 吞并国家时转移其运输船的比例
	MIN_POSSIBLE_TRAINING_MANPOWER = 100000,  -- 训练部队所需最低人力（部署线最小值）
	MIN_FIELD_TO_TRAINING_MANPOWER_RATIO = 0.75,  -- 部署部队中可被训练的最大人力比例
	CAPITULATE_STOCKPILES_RATIO = 0.5,  -- 国家投降时转移其库存装备的比例
	CAPITULATE_FUEL_RATIO = 0.5,  -- 国家投降时转移其燃料的比例
	INFRA_MAX_CONSTRUCTION_COST_EFFECT = 1,  -- 高基础设施省份对共享建筑造价的减免上限
	PRODUCTION_RESOURCE_LACK_PENALTY = -0.05,  -- 每座工厂因资源短缺导致的产出惩罚
	CIC_BANK_SPEED_BOOST_FACTOR = 0.25,  -- 民用工业银行可提供的生产速度加成倍率（0.5即50%）
	MIN_LICENSE_ACTIVE_DAYS = 30,  -- 装备许可证生效的最短天数
	BASE_LICENSE_IC_COST = 1,  -- 租借装备许可证的基础IC成本
	LICENSE_IC_COST_YEAR_INCREASE = 1,  -- 装备每超过1936一年，许可证IC成本增加量
	LICENSE_EQUIPMENT_BASE_SPEED = -0.25,  -- 生产租借装备的基础军事工厂速度修正
	LICENSE_EQUIPMENT_TECH_SPEED_PER_YEAR = -0.05,  -- 每落后最新装备一年，生产租借装备的速度惩罚
	LICENSE_EQUIPMENT_TECH_SPEED_MAX_YEARS = 4,  -- 生产租借装备速度惩罚的最大年数限制
	LICENSE_EQUIPMENT_SPEED_NOT_FACTION = -0.10,  -- 非阵营成员生产租借装备的额外速度惩罚
	LICENSE_EQUIPMENT_UPGRADE_XP_FACTOR = 2.0,  -- 升级租借装备所需的XP倍率
	LICENSE_EQUIPMENT_SPEED_NO_LICENSE = -0.50,  -- 无许可证生产外国装备的惩罚
	CONVERSION_SPEED_BONUS = 0,  -- 装备转换时的生产速度修正（当前为0）
	EQUIPMENT_MODULE_ADD_XP_COST = 5.0,  -- 为空槽添加新装备模块时的XP消耗
	EQUIPMENT_MODULE_REPLACE_XP_COST = 6.0,  -- 替换为无关模块时的XP消耗
	EQUIPMENT_MODULE_CONVERT_XP_COST = 3.0,  -- 替换为相关模块时的XP消耗
	EQUIPMENT_MODULE_REMOVE_XP_COST = 1.0,  -- 移除模块并留空槽时的XP消耗
	BASE_NAVAL_EQUIPMENT_CONVERSION_IC_COST_FACTOR = 0.2,  -- 海军装备改装时，船体工业成本中始终计入的比例
	BASE_LAND_EQUIPMENT_CONVERSION_IC_COST_FACTOR = 0.9,  -- 陆军装备转换时，底盘工业成本中始终计入的比例
	MIN_NAVAL_EQUIPMENT_CONVERSION_RESOURCE_COST_FACTOR = 0.2,  -- 海军装备改装时，战略资源消耗的最低比例
	MIN_LAND_EQUIPMENT_CONVERSION_RESOURCE_COST_FACTOR = 0,  -- 陆军装备转换时，战略资源消耗的最低比例
	SHIP_REFIT_MAX_PROGRESS_TO_CANCEL = 0.2,  -- 允许取消舰船改装的最大进度（超过此值需报废舰船）
	SHIP_REFIT_DAMAGE_TO_PROGRESS_FACTOR = 0.5,  -- 舰船改装时受损，伤害按比例转化为生产线进度损失
	MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_VALUE = 1,  -- 消费品占用工厂的绝对最小值（按数值）
	MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_PERCENT = 0.1,  -- 消费品占用工厂的最小比例（按百分比）
	INITIAL_ALLOWED_FACTORY_RATIO_FOR_REPAIRS = 1.0,  -- 自动修复时允许使用的最大工厂比例（初始为100%）
}