NIntel = {
	COUNTRY_LEVEL_INTEL_MAXIMUMS = {			-- The maximum intel a country can have over another
		100.0, -- Civilian
		100.0, -- Army
		100.0, -- Navy
		100.0, -- Airforce
	},

	-- Static sources:
	--
	-- A static source is a source that will fully decay once its origin disappear.
	-- (e.g. radar destroyed)
	--
	-- MAXIMUMS:
	-- if set to an non-empty arrays, overrides COUNTRY_LEVEL_INTEL_MAXIMUMS
	-- for this specific source (note that COUNTRY_LEVEL_INTEL_MAXIMUMS is
	-- applied after INTEL_SOURCE_XXX_MAXIMUMS)

	STATIC_INTEL_SOURCE_OPERATION_TOKENS_MAXIMUMS = {},
	STATIC_INTEL_SOURCE_BROKEN_CYPHER_MAXIMUMS = { 60.0, 60.0, 60.0, 60.0 },
	STATIC_INTEL_SOURCE_RADAR_MAXIMUMS = { 10.0, 10.0, 20.0, 20.0 },
	STATIC_INTEL_SOURCE_INTEL_NETWORK_MAXIMUMS = { 30.0, 30.0, 40.0, 30.0},

	-- Dynamic intel pool can be manipulated through the following defines:
	--
	-- FLAT_DECAY and MULT_DECAY control the rate at which the intel decays
	-- The formula is applied as follow (runs daily):
	-- NextIntel = ( Intel - FLAT_DECAY ) * MULT_DECAY
	--
	-- AGGREGAT_LOG_FACTOR and AGGREGAT_DIVISOR control the rate at which
	-- intel accumulates. It is applied to the sum of the intel generated
	-- throughout the day as follow:
	-- Aggregat = LOG_FACTOR * log( 1 + IntelOfTheDay ) + IntelOfTheDay / DIVISOR
	-- The Aggregat is then added to the pool of intel.
	-- If DIVISOR is zero then the division is evaluated to zero.
	--
	-- MAXIMUMS controls the maximum value that the pool can contribute to
	-- the final intel values.
	--
	-- ABSOLUTE_MAXIMUMS defines a ceiling for the intel in the pool that
	-- will never be exceeded. They are meant to be greater or equal to
	-- MAXIMUMS. If the array is empty, no absolute maximum is defined.

	-- Dynamic pool EVENT
	DYNAMIC_INTEL_SOURCE_EVENT_FLAT_DECAY = 0.0,
	DYNAMIC_INTEL_SOURCE_EVENT_MULT_DECAY = 0.985,
	DYNAMIC_INTEL_SOURCE_EVENT_AGGREGAT_LOG_FACTOR = 0,
	DYNAMIC_INTEL_SOURCE_EVENT_AGGREGAT_DIVISOR = 1,
	DYNAMIC_INTEL_SOURCE_EVENT_MAXIMUMS = { 40, 40, 40, 40 },
	DYNAMIC_INTEL_SOURCE_EVENT_ABSOLUTE_MAXIMUMS = { 50, 50, 50, 50 },

	-- Dynamic pool LAND_COMBAT
	DYNAMIC_INTEL_SOURCE_LAND_COMBAT_FLAT_DECAY = 0.0,
	DYNAMIC_INTEL_SOURCE_LAND_COMBAT_MULT_DECAY = 0.985,
	DYNAMIC_INTEL_SOURCE_LAND_COMBAT_AGGREGAT_LOG_FACTOR = 0.25,
	DYNAMIC_INTEL_SOURCE_LAND_COMBAT_AGGREGAT_DIVISOR = 10,
	DYNAMIC_INTEL_SOURCE_LAND_COMBAT_MAXIMUMS = { 0, 30, 5, 10 },
	DYNAMIC_INTEL_SOURCE_LAND_COMBAT_ABSOLUTE_MAXIMUMS = { 0, 40, 10, 15 },

	-- Dynamic pool NAVAL_COMBAT
	DYNAMIC_INTEL_SOURCE_NAVAL_COMBAT_FLAT_DECAY = 0.0,
	DYNAMIC_INTEL_SOURCE_NAVAL_COMBAT_MULT_DECAY = 0.985,
	DYNAMIC_INTEL_SOURCE_NAVAL_COMBAT_AGGREGAT_LOG_FACTOR = 0.02,
	DYNAMIC_INTEL_SOURCE_NAVAL_COMBAT_AGGREGAT_DIVISOR = 200,
	DYNAMIC_INTEL_SOURCE_NAVAL_COMBAT_MAXIMUMS = { 10, 0, 40, 20 },
	DYNAMIC_INTEL_SOURCE_NAVAL_COMBAT_ABSOLUTE_MAXIMUMS = { 15, 0, 45, 25 },

	-- Dynamic pool AIR_COMBAT
	DYNAMIC_INTEL_SOURCE_AIR_COMBAT_FLAT_DECAY = 0.0,
	DYNAMIC_INTEL_SOURCE_AIR_COMBAT_MULT_DECAY = 0.985,
	DYNAMIC_INTEL_SOURCE_AIR_COMBAT_AGGREGAT_LOG_FACTOR = 1,
	DYNAMIC_INTEL_SOURCE_AIR_COMBAT_AGGREGAT_DIVISOR = 2,
	DYNAMIC_INTEL_SOURCE_AIR_COMBAT_MAXIMUMS = { 0, 0, 0, 25 },
	DYNAMIC_INTEL_SOURCE_AIR_COMBAT_ABSOLUTE_MAXIMUMS = { 0, 0, 0, 30 },

	-- Dynamic pool AIR_RECON
	DYNAMIC_INTEL_SOURCE_AIR_RECON_FLAT_DECAY = 0.0,
	DYNAMIC_INTEL_SOURCE_AIR_RECON_MULT_DECAY = 0.995,
	DYNAMIC_INTEL_SOURCE_AIR_RECON_AGGREGAT_LOG_FACTOR = 0.05,
	DYNAMIC_INTEL_SOURCE_AIR_RECON_AGGREGAT_DIVISOR = 200,
	DYNAMIC_INTEL_SOURCE_AIR_RECON_MAXIMUMS = { 25, 20, 30, 20 },
	DYNAMIC_INTEL_SOURCE_AIR_RECON_ABSOLUTE_MAXIMUMS = { 30, 25, 35, 25 },

	-- Dynamic pool CAPTURED_OPERATIVE
	DYNAMIC_INTEL_SOURCE_CAPTURED_OPERATIVE_FLAT_DECAY = 0.0,
	DYNAMIC_INTEL_SOURCE_CAPTURED_OPERATIVE_MULT_DECAY = 0.95,
	DYNAMIC_INTEL_SOURCE_CAPTURED_OPERATIVE_AGGREGAT_LOG_FACTOR = 1,
	DYNAMIC_INTEL_SOURCE_CAPTURED_OPERATIVE_AGGREGAT_DIVISOR = 2,
	DYNAMIC_INTEL_SOURCE_CAPTURED_OPERATIVE_MAXIMUMS = { 50, 40, 40, 30 },
	DYNAMIC_INTEL_SOURCE_CAPTURED_OPERATIVE_ABSOLUTE_MAXIMUMS = { 50, 40, 40, 30 },

	LAND_COMBAT_ARMY_INTEL_OVER_OPPONENT_PER_INSTANCE = 1.0,			-- if the opponent has any division present, flat intel value generated py a participant against an opponent
	LAND_COMBAT_ARMY_INTEL_OVER_OPPONENT_PER_COMITTED_DIVISIONS = 0.5,		-- multiplied to the number of comitted divisions of the opponent
	LAND_COMBAT_ARMY_INTEL_OVER_OPPONENT_PER_RESERVE_DIVISIONS = 0.1,		-- same for divisions in reserve
	LAND_COMBAT_ARMY_INTEL_OVER_OPPONENT_PER_RETREATING_DIVISIONS = 0.2,		-- same for retreating divisions
	LAND_COMBAT_ARMY_INTEL_FACTOR = 0.01,						-- factor applied once all values have been added together
	LAND_COMBAT_AIR_INTEL_OVER_OPPONENT_PER_INSTANCE = 1.0,				-- if the opponent has any plane active in the, flat intel value generated by a participant against that opponent
	LAND_COMBAT_AIR_INTEL_OVER_OPPONENT_PER_PLANE = 0.1,				-- multiplied to the number of plane that opponent has in the combat
	LAND_COMBAT_AIR_INTEL_FACTOR = 0.01,						-- factor applied once all values have been added together
	RECON_INTEL_BONUS = 0.075,                                      -- each recon gives this bonus to overall gathered land intel in combat

	NAVAL_COMBAT_NAVY_INTEL_OVER_OPPONENT_PER_INSTANCE = 1.0,
	NAVAL_COMBAT_NAVY_INTEL_OVER_OPPONENT_PER_SUBMARINE = 0.2,
	NAVAL_COMBAT_NAVY_INTEL_OVER_OPPONENT_PER_SCREEN_SHIP = 0.5,
	NAVAL_COMBAT_NAVY_INTEL_OVER_OPPONENT_PER_CAPITAL_SHIP = 1.0,
	NAVAL_COMBAT_NAVY_INTEL_OVER_OPPONENT_PER_INTERNAL_PLANES = 0.05,
	NAVAL_COMBAT_NAVY_INTEL_FACTOR = 1.0,
	NAVAL_COMBAT_CIVILIAN_INTEL_OVER_OPPONENT_PER_INSTANCE = 0.0,
	NAVAL_COMBAT_CIVILIAN_INTEL_OVER_OPPONENT_PER_TRADE_CONVOY = 1.0,
	NAVAL_COMBAT_CIVILIAN_INTEL_FACTOR = 1.0,
	NAVAL_COMBAT_ARMY_INTEL_OVER_OPPONENT_PER_INSTANCE = 0.0,
	NAVAL_COMBAT_ARMY_INTEL_OVER_OPPONENT_PER_TRANSFER_CONVOY = 1.0,
	NAVAL_COMBAT_ARMY_INTEL_FACTOR = 1.0,
	NAVAL_COMBAT_AIR_INTEL_OVER_OPPONENT_PER_INSTANCE = 1.0,
	NAVAL_COMBAT_AIR_INTEL_OVER_OPPONENT_PER_INTERNAL_PLANES = 0.0,
	NAVAL_COMBAT_AIR_INTEL_OVER_OPPONENT_PER_EXTERNAL_PLANES = 0.01,
	NAVAL_COMBAT_AIR_INTEL_FACTOR = 1.0,

	NAVY_INTEL_BASE_SPOTTING_BONUS_MIN_INTEL_FOR_BONUS = 5, -- at least this intel diff is needed for start applying BASE_SPOTTING_FROM_DECRYPTION bonus
	NAVY_INTEL_BASE_SPOTTING_BONUS_MAX_INTEL_FOR_BONUS = 40, -- at this intel BASE_SPOTTING_FROM_DECRYPTION will be applied fully

	NAVY_INTEL_MINE_DAMAGE_REDUCTION_FACTOR_MIN_INTEL_FOR_BONUS = 5, -- at least this intel diff is needed for start applying NAVAL_MINES_INTEL_DIFF_FACTOR bonus
	NAVY_INTEL_MINE_DAMAGE_REDUCTION_FACTOR_MAX_INTEL_FOR_BONUS = 40, -- t this intel NAVAL_MINES_INTEL_DIFF_FACTOR will be applied fully

	AIR_COMBAT_AIR_INTEL_PER_INSTANCE = 1.0,
	AIR_COMBAT_AIR_INTEL_PER_OPPONENT_PLANE = 0.0,
	AIR_COMBAT_AIR_INTEL_FACTOR = 0.2,

	INTEL_NETWORK_NATIONAL_COVERAGE_FACTOR = 2.0,			 -- multiplied to the national coverage to deduce the fraction of the maximum value listed below that will be added to the intel against the network's target
	INTEL_NETWORK_NATIONAL_COVERAGE_NAVAL_BASE_FACTOR = 15.0, -- factor used instead of above in case you dont cover naval bases etc

	-- the maximum intel values that an intel network will provide against a target
	INTEL_NETWORK_MAX_CIVILIAN_INTEL = 20.0,
	INTEL_NETWORK_MAX_ARMY_INTEL = 20.0,
	INTEL_NETWORK_MAX_NAVY_INTEL = 25.0,				-- only apply if the network encompass a naval base controlled by the network's target
	INTEL_NETWORK_MAX_AIRFORCE_INTEL = 15.0,

	RADAR_LEVEL_INTEL_FACTOR = 1.25,					-- Multiplied to the radar level to tell the fraction of intel per covered province we get. The radar level is computed as BuildingLevel / MaxBuildingLevel.
	RADAR_INTEL_STACKING_FACTOR = 0.5,				-- Used when multiple radars cover the same province
	RADAR_BASE_INTEL_VALUES_FOR_COUNTRY_COVERAGE_PERCENTAGE = {
		-- Values are the same order as in COUNTRY_LEVEL_INTEL_MAXIMUMS
		-- Multiplied by the total radar efficiency over the provinces of
		-- a specific country divided by the number of provinces controlled
		-- by that same country.
		9.0,
		9.0,
		0.0,
		18.0,
	},
	RADAR_BASE_INTEL_VALUES_FOR_COVERED_LAND_PROVINCES = {
		-- Values are the same order as in COUNTRY_LEVEL_INTEL_MAXIMUMS
		-- Multiplied by the total radar efficiency of the provinces of
		-- a specific country divided by the individual radar's
		-- percentage of covered provinces.
		5.0,
		5.0,
		0.0,
		12.0,
	},
	RADAR_BASE_INTEL_VALUES_FOR_COVERED_SEA_PROVINCES = {
		-- Values are the same order as in COUNTRY_LEVEL_INTEL_MAXIMUMS
		-- Multiplied by the total radar efficiency of the provinces
		-- covered by the radar for each strategic region that has
		-- convoy routes and multiplied by the fraction of convoy
		-- that country has going through the region (excluding the
		-- convoys of the radar's owner)
		0.0,
		0.0,
		280.0,
		0.0,
	},
	RADAR_NAVY_INTEL_FACTOR_PER_SHIP_TYPE = {
		-- Navy intel value factored to the fraction of the country's
		-- ships in the sea zone covered by the radar, by ship type
		5.0, -- Submarine
		10.0, -- Screen ship
		20.0, -- Capital ship
		30.0, -- Carrier ship
	},
	CAPTURED_OPERATIVE_MAX_FACTOR = 35.0,	-- Define the maximum of the randomized factor, before the factor from operative is applied
	CAPTURED_OPERATIVE_MIN_FACTOR = 10.0,	-- Define the minimum of the randomized factor, before the factor from operative is applied
	CAPTURED_OPERATIVE_INTEL_YIELD = {
		-- Values are the same order as in COUNTRY_LEVEL_INTEL_MAXIMUMS
		-- Daily base intel yield from an operative, before the
		-- factors defined above are applied
		0.3,
		0.3,
		0.3,
		0.3,
	},

	RECON_PLANE_INTEL_BASE = 0.02, 				-- intel base amount for a strategic area per plane
	RECON_PLANE_LAND_DISTRIBUTION = { 10.0, 6.0, 0.0, 3.0 },    -- controls for land and sea zones how much of each intel typee is given (civ, army, navy, air)
	RECON_PLANE_SEA_DISTRIBUTION = { 0.0, 0.0, 10.0, 0.0 },

	LAND_SPOT_DECAY = 0.05,
	NAVAL_SPOT_DECAY = 1,

	ENCRYPTION_DECRYPTION_INTEL_FACTORS = {
		-- Factored to ( 1 + A.decryption ) / ( 1 + B.encryption ) to determine the intel
		-- A has over B when legacy encryption and decryption modifier are used.
		-- Note that if A.decryption is zero, the result is forced to zero
		-- In the ame order as COUNTRY_LEVEL_INTEL_MAXIMUMS
		15.0, 15.0, 15.0, 15.0
	},

	-- intel ledger defines
	CIVILIAN_PRODUCTION_RANGE_INTEL_MIN = 0.1, -- minimum value to show fuzzy factory counts below this you will get ???
	CIVILIAN_PRODUCTION_RANGE_INTEL_MAX = 0.5, -- maximum value to show fuzzy factory counts. above this you will get full count
	CIVILIAN_PRODUCTION_INTEL_RANGE_AT_LOWEST_INTEL = 0.5, -- range of intel values at lowest intel

	CIVILIAN_FUEL_RANGE_INTEL_MIN = 0.3, -- minimum value to show fuzzy factory counts below this you will get ???
	CIVILIAN_FUEL_RANGE_INTEL_MAX = 0.7, -- maximum value to show fuzzy factory counts. above this you will get full count
	CIVILIAN_FUEL_INTEL_RANGE_AT_LOWEST_INTEL = 0.5, -- range of intel values at lowest intel

	CIVILIAN_MANPOWER_RANGE_INTEL_MIN = 0.1, -- minimum value to show fuzzy factory counts below this you will get ???
	CIVILIAN_MANPOWER_RANGE_INTEL_MAX = 0.7, -- maximum value to show fuzzy factory counts. above this you will get full count
	CIVILIAN_MANPOWER_INTEL_RANGE_AT_LOWEST_INTEL = 0.5, -- range of intel values at lowest intel

	CIVILIAN_CONVOYS_RANGE_INTEL_MIN = 0.1, -- minimum value to show fuzzy factory counts below this you will get ???
	CIVILIAN_CONVOYS_INTEL_RANGE_AT_LOWEST_INTEL = 0.5, -- range of intel values at lowest intel

	CIVILIAN_TRUCKS_RANGE_INTEL_MIN = 0.1, -- minimum value to show fuzzy factory counts below this you will get ???
	CIVILIAN_TRUCKS_RANGE_INTEL_MAX = 0.5, -- maximum value to show fuzzy factory counts. above this you will get full count
	CIVILIAN_TRUCKS_INTEL_RANGE_AT_LOWEST_INTEL = 0.5, -- range of intel values at lowest intel

	CIVILIAN_TRAINS_RANGE_INTEL_MIN = 0.1, -- minimum value to show fuzzy factory counts below this you will get ???
	CIVILIAN_TRAINS_RANGE_INTEL_MAX = 0.5, -- maximum value to show fuzzy factory counts. above this you will get full count
	CIVILIAN_TRAINS_INTEL_RANGE_AT_LOWEST_INTEL = 0.5, -- range of intel values at lowest intel

	CIVILIAN_SUPPLY_RANGE_INTEL_MIN = 0.1, -- minimum value to show fuzzy factory counts below this you will get ???
	CIVILIAN_SUPPLY_RANGE_INTEL_MAX = 0.5, -- maximum value to show fuzzy factory counts. above this you will get full count
	CIVILIAN_SUPPLY_INTEL_RANGE_AT_LOWEST_INTEL = 0.5, -- range of intel values at lowest intel

	CIVILIAN_TRADE_SHOW_TRADE_AMOUNTS = 0.0, -- minimum value to show how much a country trades a resource
	CIVILIAN_TRADE_SHOW_TRADE_PARTNERS = 0.1, -- minimum value to show who a country trades with
	CIVILIAN_MIN_INTEL_FOR_RESOURCE_ROUTES_TOOLTIPS = 0.9, -- minimum value to show convoy routes for resource transfer
	CIVILIAN_MIN_INTEL_FOR_TRADE_ROUTES = 0.7, -- minimum value to show trade routes on map
	CIVILIAN_MIN_INTEL_FOR_RESOURCE_ORIGIN_ROUTES = 0.5, -- minimum value to show resource transfers to mainland on map

	ARMY_MIN_INTEL_FOR_SUPPLY_ROUTES = 0.5, -- minimum value to show convoy routes for supply transfer
	ARMY_MIN_INTEL_FOR_SUPPLY_ROUTES_TOOLTIPS = 0.7, -- minimum value to show convoy route tooltips for supply transfer

	CIVILIAN_INTEL_NEEDED_TO_SHOW_ANTI_AIR_REDUCTION = 0.3, -- minimum value to show anti air damage reduction

	CIVILIAN_INTEL_NEEDED_TO_SHOW_FOCUS_TREE = 0.5, -- min required intel to focus tree with taken focuses
	CIVILIAN_INTEL_NEEDED_TO_SHOW_CURRENT_FOCUS = 0.7,  -- min required intel to show currently focus
	CIVILIAN_INTEL_NEEDED_TO_SHOW_CURRENT_FOCUS_PROGRESS = 0.7,  -- min required intel to show current focus progress

	CIVILIAN_MIN_INTEL_TO_SHOW_INDUSTRY_GRAPH = 0.30,
	CIVILIAN_MIN_INTEL_TO_SHOW_CONVOYS_GRAPH = 0.70,
	CIVILIAN_MIN_INTEL_TO_SHOW_BOMBERS_GRAPH = 0.8,
	CIVILIAN_MIN_INTEL_TO_SHOW_TRUCKS_GRAPH = 0.5,
	CIVILIAN_MIN_INTEL_TO_SHOW_TRAINS_GRAPH = 0.5,

	CIVILIAN_MIN_INTEL_TO_SHOW_RAIL_STAUS = 0.4, -- when mousing over supply map mode, shows damage/construction status

	OLD_TECH_COUNT_NUM_DAYS = 180, -- num days after researched to consider a tech as "old"
	INTEL_TO_SHOW_TECH_COUNT = { 0.5, 0.3, 0.3, 0.3 },  -- minimum value to show current tech count and current doctrine
	INTEL_TO_SHOW_PREVIOUSLY_RESEARCHED = { 0.7, 0.7, 0.7, 0.7 }, -- minimum value to show previously researched tech
	INTEL_TO_SHOW_CURRENTLY_RESEARCHED = { 0.8, 0.8, 0.8, 0.8 }, -- minimum value to show currently being researched tech

	INTEL_TO_SHOW_IDEAS = { 0.0, 0.0, 0.0, 0.0 },

	ARMY_ARMY_COUNT_RANGE_INTEL_MIN = 0.05,
	ARMY_ARMY_COUNT_RANGE_INTEL_MAX = 0.7,
	ARMY_ARMY_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.8,

	ARMY_SPECIAL_FORCES_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.7,

	ARMY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MIN = 0.1,
	ARMY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MAX = 0.7,
	ARMY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,
	ARMY_MIN_INTEL_TO_SHOW_EQUIPMENT_RATIO = 0.7,

	ARMY_MIN_INTEL_TO_SHOW_BASIC_TEMPLATE_INFO = 0.3,
	ARMY_TEMPLATE_UNIT_COUNT_INTEL_MIN = 0.5,
	ARMY_TEMPLATE_UNIT_COUNT_INTEL_MAX = 0.7,
	ARMY_TEMPLATE_UNIT_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 1.0,
	ARMY_MIN_INTEL_TO_SHOW_EXACT_TEMPLATE_INFO = 0.8,

	ARMY_STOCKPILE_COUNT_INTEL_MIN = 0.3,
	ARMY_STOCKPILE_COUNT_INTEL_MAX = 0.7,
	ARMY_STOCKPILE_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	ARMY_MIN_INTEL_TO_SHOW_EQUIPMENT_DESIGN_DETAILS = 0.8,

	ARMY_MIN_INTEL_RATIO_NEEDED_FOR_DISPLAYING_FAKE_ENEMY_INTEL_IN_LEDGER = 0.9,
	ARMY_MIN_INTEL_RATIO_NEEDED_FOR_REVEALING_FAKE_ENEMY_INTEL = 0.9,

	ARMY_INTEL_COMBAT_BONUS_MAX_BONUS = 0.15, -- max combat bonus that will apply when intel is high enough
	ARMY_INTEL_COMBAT_BONUS_FACTOR_ATTACK = 1.0, -- multiplier for attack value of intel combat bonus
	ARMY_INTEL_COMBAT_BONUS_FACTOR_DEFENSE = 1.0, -- multiplier for defense value of intel combat bonus

	ARMY_INTEL_COMBAT_BONUS_MIN_INTEL_FOR_BONUS = 5, -- min intel needed to start applying ARMY_INTEL_COMBAT_BONUS_MAX_BONUS
	ARMY_INTEL_COMBAT_BONUS_MAX_INTEL_FOR_BONUS = 50, -- intel needed to fully apply ARMY_INTEL_COMBAT_BONUS_MAX_BONUS

	NAVAL_SUPREMACY_INTEL_LOW = 0.4,								-- we need more intel than this to get any supremacy
	NAVAL_SUPREMACY_INTEL_LOW_SUPREMACY_PENALTY_START = 0.1,		-- supremacy is reduced to NAVAL_SUPREMACY_INTEL_LOW_SUPREMACY_MIN_PENALTY at or below this intel
	NAVAL_SUPREMACY_INTEL_LOW_SUPREMACY_MIN_PENALTY = 0.5, -- you get this much supremacy at NAVAL_SUPREMACY_INTEL_LOW_SUPREMACY_PENALTY_START and scales up to 1 at NAVAL_SUPREMACY_INTEL_LOW

	NAVY_FLEET_COUNT_INTEL_MIN = 0.1,
	NAVY_FLEET_COUNT_INTEL_MAX = 0.3,
	NAVY_FLEET_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	NAVY_TASKFORCE_COUNT_INTEL_MIN = 0.3,
	NAVY_TASKFORCE_COUNT_INTEL_MAX = 0.7,
	NAVY_TASKFORCE_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	NAVY_SHIP_COUNT_INTEL_MIN = 0.1,
	NAVY_SHIP_COUNT_INTEL_MAX = 0.8,
	NAVY_SHIP_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	NAVY_MIN_INTEL_TO_SHOW_EXISTING_CATEGORY_TYPES = 0.1,   --this is about disaplying ships by class category
	NAVY_SHIP_TYPE_COUNT_INTEL_MIN = 0.3,					--this range is used both when for disaplying counts by class and counts by variant
	NAVY_SHIP_TYPE_COUNT_INTEL_MAX = 0.7,
	NAVY_SHIP_TYPE_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	NAVY_MIN_INTEL_TO_SHOW_SHIP_CLASSES = 0.5, --this unclocks the display of a given variant
	NAVY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MIN = 0.05,
	NAVY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MAX = 0.7,
	NAVY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	NAVY_MIN_INTEL_TO_SHOW_SHIP_DESIGN_DETAILS = 0.8,

	AIR_AIRWING_COUNT_INTEL_MIN = 0.0,
	AIR_AIRWING_COUNT_INTEL_MAX = 0.7,
	AIR_AIRWING_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	AIR_MIN_INTEL_TO_SHOW_AIRWING_CLASSES = 0.3,
	AIR_WING_TYPE_COUNT_INTEL_MIN = 0.5,
	AIR_WING_TYPE_COUNT_INTEL_MAX = 0.7,
	AIR_WING_TYPE_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	AIR_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MIN = 0.1,
	AIR_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MAX = 0.7,
	AIR_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

    RAID_MIN_INTEL_FOR_WARNING_ON_LAUNCH = 0.1,           -- how much intel (of the relevant type) is needed to show a warning when raid is launched
    RAID_MIN_INTEL_FOR_WARNING_HALFWAY_TO_LAUNCH = 0.5,   -- how much intel (of the relevant type) is needed to show a warning halfway through preparation
                                                          --     (this limit is a dummy value only used for communicating the role of intel in the intel ledger )
                                                          --     (in reality, detection scales linearly with intel. 70% intel = detection at 30% preparation, 50% intel = detection at 50% preparation, etc.
    RAID_MIN_INTEL_FOR_WARNING_EARLY_PREPARATION = 0.8,   -- how much intel (of the relevant type) is needed to show a warning early in the preparation
                                                          --     (this limit is a dummy value only used for communicating the role of intel in the intel ledger )
                                                          --     (in reality, detection scales linearly with intel. 70% intel = detection at 30% preparation, 50% intel = detection at 50% preparation, etc.

	CIVILIAN_MAPICON_INDUSTRY_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.7,

	MAP_INTEL_VISIBILITY_CUTOFFS = { -- how much map intel is gained with intel over a country. first number is threshold, second is amount of intel map intel gained
		0.1, -50,
		0.4, 0,
		0.6, 50,
		1.0, 100,
	},

	-- these are used in some triggers
	ARMY_AVG_ARMOR_INTEL_MIN = 0.0,
	ARMY_AVG_ARMOR_INTEL_MAX = 0.5,
	ARMY_AVG_ARMOR_RANGE_AT_LOWEST_INTEL = 1.0,

	ARMY_MAX_ARMOR_INTEL_MIN = 0.0,
	ARMY_MAX_ARMOR_INTEL_MAX = 0.5,
	ARMY_MAX_ARMOR_RANGE_AT_LOWEST_INTEL = 1.0,

	ARMY_AVG_PIERCING_INTEL_MIN = 0.0,
	ARMY_AVG_PIERCING_INTEL_MAX = 0.5,
	ARMY_AVG_PIERCING_RANGE_AT_LOWEST_INTEL = 1.0,

	ARMY_MAX_PIERCING_INTEL_MIN = 0.0,
	ARMY_MAX_PIERCING_INTEL_MAX = 0.5,
	ARMY_MAX_PIERCING_RANGE_AT_LOWEST_INTEL = 1.0,
	--~

	NAVY_MAPICON_MISSION_COUNT_INTEL_MIN = 0.5,  -- min intel to show assigned naval missions
	NAVY_MAPICON_MISSION_COUNT_INTEL_MAX = 0.8,  -- min intel to show assigned naval missions with perfect accuracy, and taskforces count

	NAVY_MAPICON_SHOW_ALL_NAVAL_PORTS = 0.3,  -- min intel to show all naval ports (otherwise you will only see nearby ones)
	NAVY_MAPICON_NAVAL_PORT_VISIBILITY_DETAIL_THRESHOLDS = { -- how detailed the post tooltips will be
		0.0,	-- for no intel
		0.1,	-- show port level
		0.3,	-- show fuzzy taskforce count
		0.7,	-- show full taskforce count
		0.8,	-- show taskforce details
	},
	NAVY_MAPICON_NAVAL_PORT_TASKFORCE_FUZZY_THRESHOLD = 0.5,

	AIR_MAPICON_MISSION_COUNT_INTEL_MIN = {
		0.3, -- AIR_SUPERIORITY
		0.3, -- CAS
		0.3, -- INTERCEPTION
		0.3, -- STRATEGIC_BOMBER
		0.3, -- NAVAL_BOMBER
		0.3, -- DROP_NUKE
		0.3, -- PARADROP
		0.3, -- NAVAL_KAMIKAZE
        0.3, -- PORT_STRIKE
		0.3, -- ATTACK_LOGISTICS
		0.3, -- AIR_SUPPLY
		0.3, -- TRAINING
		0.3, -- NAVAL_MINES_PLANTING
		0.3, -- NAVAL_MINES_SWEEPING
		0.3, -- RECON
		0.3, -- NAVAL_PATROL
	},
	AIR_MAPICON_MISSION_COUNT_INTEL_MAX = {
		0.6, -- AIR_SUPERIORITY
		0.6, -- CAS
		0.6, -- INTERCEPTION
		0.6, -- STRATEGIC_BOMBER
		0.6, -- NAVAL_BOMBER
		0.6, -- DROP_NUKE
		0.6, -- PARADROP
		0.6, -- NAVAL_KAMIKAZE
        0.6, -- PORT_STRIKE
		0.6, -- ATTACK_LOGISTICS
		0.6, -- AIR_SUPPLY
		0.6, -- TRAINING
		0.6, -- NAVAL_MINES_PLANTING
		0.6, -- NAVAL_MINES_SWEEPING
		0.6, -- RECON
		0.6, -- NAVAL_PATROL
	},
	AIR_MAPICON_MISSION_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = {
		0.5, -- AIR_SUPERIORITY
		0.5, -- CAS
		0.5, -- INTERCEPTION
		0.5, -- STRATEGIC_BOMBER
		0.5, -- NAVAL_BOMBER
		0.5, -- DROP_NUKE
		0.5, -- PARADROP
		0.5, -- NAVAL_KAMIKAZE
        0.5, -- PORT_STRIKE
		0.5, -- ATTACK_LOGISTICS
		0.5, -- AIR_SUPPLY
		0.5, -- TRAINING
		0.5, -- NAVAL_MINES_PLANTING
		0.5, -- NAVAL_MINES_SWEEPING
		0.5, -- RECON
		0.5, -- NAVAL_PATROL
	},

	AIR_MAPICON_SHOW_ALL_AIR_PORTS = 0.3,  -- min intel to show all air ports (otherwise you will only see nearby ones)
	AIR_MAPICON_AIR_PORT_VISIBILITY_DETAIL_THRESHOLDS = { -- how detailed the post tooltips will be
		0.0,	-- for no intel
		0.3,	-- show fuzzy air plane count
		0.7,	-- show full air count
		0.8,	-- show air plane details
	},
	AIR_MAPICON_AIR_PORT_PLANE_FUZZY_THRESHOLD = 0.5,
	AIR_MIN_INTEL_TO_SHOW_EQUIPMENT_DESIGN_DETAILS = 0.8,

	-- ~intel ledger defines
},

NIntel = { --情报与侦查
	COUNTRY_LEVEL_INTEL_MAXIMUMS = {			-- 国家间情报等级的最大上限
		100.0, -- 民用
		100.0, -- 陆军
		100.0, -- 海军
		100.0, -- 空军
	},

	-- 静态来源：
	--
	-- 静态来源是指一旦其来源消失（如雷达被摧毁），将完全衰减。
	--
	-- 最大值：
	-- 如果设置为非空数组，则覆盖 COUNTRY_LEVEL_INTEL_MAXIMUMS
	-- 仅适用于该特定来源（注意 COUNTRY_LEVEL_INTEL_MAXIMUMS 会在之后应用）

	STATIC_INTEL_SOURCE_OPERATION_TOKENS_MAXIMUMS = {},
	STATIC_INTEL_SOURCE_BROKEN_CYPHER_MAXIMUMS = { 60.0, 60.0, 60.0, 60.0 }, -- 破译密码
	STATIC_INTEL_SOURCE_RADAR_MAXIMUMS = { 10.0, 10.0, 20.0, 20.0 }, -- 雷达
	STATIC_INTEL_SOURCE_INTEL_NETWORK_MAXIMUMS = { 30.0, 30.0, 40.0, 30.0}, -- 情报网络

	-- 动态情报池可通过以下参数控制：
	--
	-- FLAT_DECAY 和 MULT_DECAY 控制情报的衰减速度
	-- 每日计算公式如下：
	-- 下一日情报 = (当前情报 - FLAT_DECAY) * MULT_DECAY
	--
	-- AGGREGAT_LOG_FACTOR 和 AGGREGAT_DIVISOR 控制情报积累速度
	-- 应用于每日情报总和，公式如下：
	-- 累计值 = LOG_FACTOR * log(1 + 当日情报) + 当日情报 / DIVISOR
	-- 累计值将加入情报池
	-- 如果 DIVISOR 为 0，则除法结果为 0
	--
	-- MAXIMUMS 控制该来源对最终情报值的最大贡献
	--
	-- ABSOLUTE_MAXIMUMS 定义情报池的绝对上限
	-- 应大于或等于 MAXIMUMS。若为空，则无上限

	-- 动态来源：事件
	DYNAMIC_INTEL_SOURCE_EVENT_FLAT_DECAY = 0.0,
	DYNAMIC_INTEL_SOURCE_EVENT_MULT_DECAY = 0.985,
	DYNAMIC_INTEL_SOURCE_EVENT_AGGREGAT_LOG_FACTOR = 0,
	DYNAMIC_INTEL_SOURCE_EVENT_AGGREGAT_DIVISOR = 1,
	DYNAMIC_INTEL_SOURCE_EVENT_MAXIMUMS = { 40, 40, 40, 40 },
	DYNAMIC_INTEL_SOURCE_EVENT_ABSOLUTE_MAXIMUMS = { 50, 50, 50, 50 },

	-- 动态来源：陆战
	DYNAMIC_INTEL_SOURCE_LAND_COMBAT_FLAT_DECAY = 0.0,
	DYNAMIC_INTEL_SOURCE_LAND_COMBAT_MULT_DECAY = 0.985,
	DYNAMIC_INTEL_SOURCE_LAND_COMBAT_AGGREGAT_LOG_FACTOR = 0.25,
	DYNAMIC_INTEL_SOURCE_LAND_COMBAT_AGGREGAT_DIVISOR = 10,
	DYNAMIC_INTEL_SOURCE_LAND_COMBAT_MAXIMUMS = { 0, 30, 5, 10 },
	DYNAMIC_INTEL_SOURCE_LAND_COMBAT_ABSOLUTE_MAXIMUMS = { 0, 40, 10, 15 },

	-- 动态来源：海战
	DYNAMIC_INTEL_SOURCE_NAVAL_COMBAT_FLAT_DECAY = 0.0,
	DYNAMIC_INTEL_SOURCE_NAVAL_COMBAT_MULT_DECAY = 0.985,
	DYNAMIC_INTEL_SOURCE_NAVAL_COMBAT_AGGREGAT_LOG_FACTOR = 0.02,
	DYNAMIC_INTEL_SOURCE_NAVAL_COMBAT_AGGREGAT_DIVISOR = 200,
	DYNAMIC_INTEL_SOURCE_NAVAL_COMBAT_MAXIMUMS = { 10, 0, 40, 20 },
	DYNAMIC_INTEL_SOURCE_NAVAL_COMBAT_ABSOLUTE_MAXIMUMS = { 15, 0, 45, 25 },

	-- 动态来源：空战
	DYNAMIC_INTEL_SOURCE_AIR_COMBAT_FLAT_DECAY = 0.0,
	DYNAMIC_INTEL_SOURCE_AIR_COMBAT_MULT_DECAY = 0.985,
	DYNAMIC_INTEL_SOURCE_AIR_COMBAT_AGGREGAT_LOG_FACTOR = 1,
	DYNAMIC_INTEL_SOURCE_AIR_COMBAT_AGGREGAT_DIVISOR = 2,
	DYNAMIC_INTEL_SOURCE_AIR_COMBAT_MAXIMUMS = { 0, 0, 0, 25 },
	DYNAMIC_INTEL_SOURCE_AIR_COMBAT_ABSOLUTE_MAXIMUMS = { 0, 0, 0, 30 },

	-- 动态来源：空中侦察
	DYNAMIC_INTEL_SOURCE_AIR_RECON_FLAT_DECAY = 0.0,
	DYNAMIC_INTEL_SOURCE_AIR_RECON_MULT_DECAY = 0.995,
	DYNAMIC_INTEL_SOURCE_AIR_RECON_AGGREGAT_LOG_FACTOR = 0.05,
	DYNAMIC_INTEL_SOURCE_AIR_RECON_AGGREGAT_DIVISOR = 200,
	DYNAMIC_INTEL_SOURCE_AIR_RECON_MAXIMUMS = { 25, 20, 30, 20 },
	DYNAMIC_INTEL_SOURCE_AIR_RECON_ABSOLUTE_MAXIMUMS = { 30, 25, 35, 25 },

	-- 动态来源：被俘特工
	DYNAMIC_INTEL_SOURCE_CAPTURED_OPERATIVE_FLAT_DECAY = 0.0,
	DYNAMIC_INTEL_SOURCE_CAPTURED_OPERATIVE_MULT_DECAY = 0.95,
	DYNAMIC_INTEL_SOURCE_CAPTURED_OPERATIVE_AGGREGAT_LOG_FACTOR = 1,
	DYNAMIC_INTEL_SOURCE_CAPTURED_OPERATIVE_AGGREGAT_DIVISOR = 2,
	DYNAMIC_INTEL_SOURCE_CAPTURED_OPERATIVE_MAXIMUMS = { 50, 40, 40, 30 },
	DYNAMIC_INTEL_SOURCE_CAPTURED_OPERATIVE_ABSOLUTE_MAXIMUMS = { 50, 40, 40, 30 },

	LAND_COMBAT_ARMY_INTEL_OVER_OPPONENT_PER_INSTANCE = 1.0, -- 如果敌方有师在场，每实例基础陆军情报
	LAND_COMBAT_ARMY_INTEL_OVER_OPPONENT_PER_COMITTED_DIVISIONS = 0.5, -- 乘以敌方投入的师数量
	LAND_COMBAT_ARMY_INTEL_OVER_OPPONENT_PER_RESERVE_DIVISIONS = 0.1, -- 同上，预备师
	LAND_COMBAT_ARMY_INTEL_OVER_OPPONENT_PER_RETREATING_DIVISIONS = 0.2, -- 同上，撤退师
	LAND_COMBAT_ARMY_INTEL_FACTOR = 0.01, -- 所有值相加后应用的总系数
	LAND_COMBAT_AIR_INTEL_OVER_OPPONENT_PER_INSTANCE = 1.0, -- 敌方有飞机参战时基础空军情报
	LAND_COMBAT_AIR_INTEL_OVER_OPPONENT_PER_PLANE = 0.1, -- 乘以敌方参战飞机数量
	LAND_COMBAT_AIR_INTEL_FACTOR = 0.01, -- 总系数
	RECON_INTEL_BONUS = 0.075, -- 每点侦察在陆战中提供的额外情报加成

	NAVAL_COMBAT_NAVY_INTEL_OVER_OPPONENT_PER_INSTANCE = 1.0,
	NAVAL_COMBAT_NAVY_INTEL_OVER_OPPONENT_PER_SUBMARINE = 0.2,
	NAVAL_COMBAT_NAVY_INTEL_OVER_OPPONENT_PER_SCREEN_SHIP = 0.5,
	NAVAL_COMBAT_NAVY_INTEL_OVER_OPPONENT_PER_CAPITAL_SHIP = 1.0,
	NAVAL_COMBAT_NAVY_INTEL_OVER_OPPONENT_PER_INTERNAL_PLANES = 0.05,
	NAVAL_COMBAT_NAVY_INTEL_FACTOR = 1.0,
	NAVAL_COMBAT_CIVILIAN_INTEL_OVER_OPPONENT_PER_INSTANCE = 0.0,
	NAVAL_COMBAT_CIVILIAN_INTEL_OVER_OPPONENT_PER_TRADE_CONVOY = 1.0,
	NAVAL_COMBAT_CIVILIAN_INTEL_FACTOR = 1.0,
	NAVAL_COMBAT_ARMY_INTEL_OVER_OPPONENT_PER_INSTANCE = 0.0,
	NAVAL_COMBAT_ARMY_INTEL_OVER_OPPONENT_PER_TRANSFER_CONVOY = 1.0,
	NAVAL_COMBAT_ARMY_INTEL_FACTOR = 1.0,
	NAVAL_COMBAT_AIR_INTEL_OVER_OPPONENT_PER_INSTANCE = 1.0,
	NAVAL_COMBAT_AIR_INTEL_OVER_OPPONENT_PER_INTERNAL_PLANES = 0.0,
	NAVAL_COMBAT_AIR_INTEL_OVER_OPPONENT_PER_EXTERNAL_PLANES = 0.01,
	NAVAL_COMBAT_AIR_INTEL_FACTOR = 1.0,

	NAVY_INTEL_BASE_SPOTTING_BONUS_MIN_INTEL_FOR_BONUS = 5, -- 至少此情报值才开始应用解密加成
	NAVY_INTEL_BASE_SPOTTING_BONUS_MAX_INTEL_FOR_BONUS = 40, -- 达到此情报值时完全应用解密加成

	NAVY_INTEL_MINE_DAMAGE_REDUCTION_FACTOR_MIN_INTEL_FOR_BONUS = 5, -- 至少此情报值才开始应用水雷减伤
	NAVY_INTEL_MINE_DAMAGE_REDUCTION_FACTOR_MAX_INTEL_FOR_BONUS = 40, -- 达到此情报值时完全应用水雷减伤

	AIR_COMBAT_AIR_INTEL_PER_INSTANCE = 1.0,
	AIR_COMBAT_AIR_INTEL_PER_OPPONENT_PLANE = 0.0,
	AIR_COMBAT_AIR_INTEL_FACTOR = 0.2,

	INTEL_NETWORK_NATIONAL_COVERAGE_FACTOR = 2.0, -- 全国覆盖率乘以该系数，决定情报网络对目标的最大情报贡献比例
	INTEL_NETWORK_NATIONAL_COVERAGE_NAVAL_BASE_FACTOR = 15.0, -- 若未覆盖海军基地等，使用此系数代替

	-- 情报网络对目标的最大情报值
	INTEL_NETWORK_MAX_CIVILIAN_INTEL = 20.0,
	INTEL_NETWORK_MAX_ARMY_INTEL = 20.0,
	INTEL_NETWORK_MAX_NAVY_INTEL = 25.0, -- 仅当网络覆盖目标控制的海军基地时生效
	INTEL_NETWORK_MAX_AIRFORCE_INTEL = 15.0,

	RADAR_LEVEL_INTEL_FACTOR = 1.25, -- 雷达等级乘以该系数，决定每覆盖省份的情报比例
	RADAR_INTEL_STACKING_FACTOR = 0.5, -- 多个雷达覆盖同一省份时的叠加系数
	RADAR_BASE_INTEL_VALUES_FOR_COUNTRY_COVERAGE_PERCENTAGE = {
		-- 顺序与 COUNTRY_LEVEL_INTEL_MAXIMUMS 一致
		-- 乘以雷达对某国所有省份的总效率 / 该国控制省份数
		9.0,
		9.0,
		0.0,
		18.0,
	},
	RADAR_BASE_INTEL_VALUES_FOR_COVERED_LAND_PROVINCES = {
		-- 顺序同上，乘以雷达对某国覆盖省份的总效率 / 单个雷达覆盖比例
		5.0,
		5.0,
		0.0,
		12.0,
	},
	RADAR_BASE_INTEL_VALUES_FOR_COVERED_SEA_PROVINCES = {
		-- 顺序同上，乘以雷达对海域的总效率，并乘以该国在该区域护航比例
		0.0,
		0.0,
		280.0,
		0.0,
	},
	RADAR_NAVY_INTEL_FACTOR_PER_SHIP_TYPE = {
		-- 按舰船类型对雷达海军情报的倍率
		5.0, -- 潜艇
		10.0, -- 屏护舰
		20.0, -- 主力舰
		30.0, -- 航母
	},
	CAPTURED_OPERATIVE_MAX_FACTOR = 35.0, -- 特工被俘前的随机因子最大值
	CAPTURED_OPERATIVE_MIN_FACTOR = 10.0, -- 特工被俘前的随机因子最小值
	CAPTURED_OPERATIVE_INTEL_YIELD = {
		-- 顺序与 COUNTRY_LEVEL_INTEL_MAXIMUMS 一致
		-- 被俘特工每日基础情报产出，应用上述因子前
		0.3,
		0.3,
		0.3,
		0.3,
	},

	RECON_PLANE_INTEL_BASE = 0.02, -- 每架侦察机对战略区域的基础情报产出
	RECON_PLANE_LAND_DISTRIBUTION = { 10.0, 6.0, 0.0, 3.0 }, -- 控制陆地区域中各类情报的分配比例（民用、陆军、海军、空军）
	RECON_PLANE_SEA_DISTRIBUTION = { 0.0, 0.0, 10.0, 0.0 }, -- 控制海域中各类情报的分配比例

	LAND_SPOT_DECAY = 0.05, -- 陆地侦察衰减
	NAVAL_SPOT_DECAY = 1,   -- 海军侦察衰减

	ENCRYPTION_DECRYPTION_INTEL_FACTORS = {
		-- 应用于 (1 + A的解密) / (1 + B的加密) 以决定A对B的情报
		-- 若A的解密为0，则结果强制为0
		-- 顺序与 COUNTRY_LEVEL_INTEL_MAXIMUMS 一致
		15.0, 15.0, 15.0, 15.0
	},

	-- 情报总览界面相关
	CIVILIAN_PRODUCTION_RANGE_INTEL_MIN = 0.1, -- 低于此值显示模糊工厂数量（显示为???）
	CIVILIAN_PRODUCTION_RANGE_INTEL_MAX = 0.5, -- 高于此值显示完整工厂数量
	CIVILIAN_PRODUCTION_INTEL_RANGE_AT_LOWEST_INTEL = 0.5, -- 最低情报时的模糊范围

	CIVILIAN_FUEL_RANGE_INTEL_MIN = 0.3,
	CIVILIAN_FUEL_RANGE_INTEL_MAX = 0.7,
	CIVILIAN_FUEL_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	CIVILIAN_MANPOWER_RANGE_INTEL_MIN = 0.1,
	CIVILIAN_MANPOWER_RANGE_INTEL_MAX = 0.7,
	CIVILIAN_MANPOWER_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	CIVILIAN_CONVOYS_RANGE_INTEL_MIN = 0.1,
	CIVILIAN_CONVOYS_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	CIVILIAN_TRUCKS_RANGE_INTEL_MIN = 0.1,
	CIVILIAN_TRUCKS_RANGE_INTEL_MAX = 0.5,
	CIVILIAN_TRUCKS_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	CIVILIAN_TRAINS_RANGE_INTEL_MIN = 0.1,
	CIVILIAN_TRAINS_RANGE_INTEL_MAX = 0.5,
	CIVILIAN_TRAINS_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	CIVILIAN_SUPPLY_RANGE_INTEL_MIN = 0.1,
	CIVILIAN_SUPPLY_RANGE_INTEL_MAX = 0.5,
	CIVILIAN_SUPPLY_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	CIVILIAN_TRADE_SHOW_TRADE_AMOUNTS = 0.0, -- 最低情报值，显示资源贸易数量
	CIVILIAN_TRADE_SHOW_TRADE_PARTNERS = 0.1, -- 最低情报值，显示贸易对象
	CIVILIAN_MIN_INTEL_FOR_RESOURCE_ROUTES_TOOLTIPS = 0.9, -- 最低情报值，显示资源运输航线提示
	CIVILIAN_MIN_INTEL_FOR_TRADE_ROUTES = 0.7, -- 最低情报值，在地图上显示贸易路线
	CIVILIAN_MIN_INTEL_FOR_RESOURCE_ORIGIN_ROUTES = 0.5, -- 最低情报值，显示资源运输至本土的路线

	ARMY_MIN_INTEL_FOR_SUPPLY_ROUTES = 0.5, -- 最低情报值，显示补给运输航线
	ARMY_MIN_INTEL_FOR_SUPPLY_ROUTES_TOOLTIPS = 0.7, -- 最低情报值，显示补给航线提示

	CIVILIAN_INTEL_NEEDED_TO_SHOW_ANTI_AIR_REDUCTION = 0.3, -- 最低情报值，显示防空减伤

	CIVILIAN_INTEL_NEEDED_TO_SHOW_FOCUS_TREE = 0.5, -- 最低情报值，显示已完成国策树
	CIVILIAN_INTEL_NEEDED_TO_SHOW_CURRENT_FOCUS = 0.7, -- 最低情报值，显示当前国策
	CIVILIAN_INTEL_NEEDED_TO_SHOW_CURRENT_FOCUS_PROGRESS = 0.7, -- 最低情报值，显示当前国策进度

	CIVILIAN_MIN_INTEL_TO_SHOW_INDUSTRY_GRAPH = 0.30,
	CIVILIAN_MIN_INTEL_TO_SHOW_CONVOYS_GRAPH = 0.70,
	CIVILIAN_MIN_INTEL_TO_SHOW_BOMBERS_GRAPH = 0.8,
	CIVILIAN_MIN_INTEL_TO_SHOW_TRUCKS_GRAPH = 0.5,
	CIVILIAN_MIN_INTEL_TO_SHOW_TRAINS_GRAPH = 0.5,

	CIVILIAN_MIN_INTEL_TO_SHOW_RAIL_STAUS = 0.4, -- 鼠标悬停供应地图时，显示铁路状态/建设状态

	OLD_TECH_COUNT_NUM_DAYS = 180, -- 研究后多少天内视为“旧科技”
	INTEL_TO_SHOW_TECH_COUNT = { 0.5, 0.3, 0.3, 0.3 }, -- 最低情报值，显示当前科技与学说数量
	INTEL_TO_SHOW_PREVIOUSLY_RESEARCHED = { 0.7, 0.7, 0.7, 0.7 }, -- 最低情报值，显示已研究科技
	INTEL_TO_SHOW_CURRENTLY_RESEARCHED = { 0.8, 0.8, 0.8, 0.8 }, -- 最低情报值，显示当前正在研究的科技

	INTEL_TO_SHOW_IDEAS = { 0.0, 0.0, 0.0, 0.0 }, -- 最低情报值，显示国家精神

	ARMY_ARMY_COUNT_RANGE_INTEL_MIN = 0.05,
	ARMY_ARMY_COUNT_RANGE_INTEL_MAX = 0.7,
	ARMY_ARMY_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.8,

	ARMY_SPECIAL_FORCES_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.7,

	ARMY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MIN = 0.1,
	ARMY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MAX = 0.7,
	ARMY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,
	ARMY_MIN_INTEL_TO_SHOW_EQUIPMENT_RATIO = 0.7,

	ARMY_MIN_INTEL_TO_SHOW_BASIC_TEMPLATE_INFO = 0.3,
	ARMY_TEMPLATE_UNIT_COUNT_INTEL_MIN = 0.5,
	ARMY_TEMPLATE_UNIT_COUNT_INTEL_MAX = 0.7,
	ARMY_TEMPLATE_UNIT_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 1.0,
	ARMY_MIN_INTEL_TO_SHOW_EXACT_TEMPLATE_INFO = 0.8,

	ARMY_STOCKPILE_COUNT_INTEL_MIN = 0.3,
	ARMY_STOCKPILE_COUNT_INTEL_MAX = 0.7,
	ARMY_STOCKPILE_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	ARMY_MIN_INTEL_TO_SHOW_EQUIPMENT_DESIGN_DETAILS = 0.8,

	ARMY_MIN_INTEL_RATIO_NEEDED_FOR_DISPLAYING_FAKE_ENEMY_INTEL_IN_LEDGER = 0.9,
	ARMY_MIN_INTEL_RATIO_NEEDED_FOR_REVEALING_FAKE_ENEMY_INTEL = 0.9,

	ARMY_INTEL_COMBAT_BONUS_MAX_BONUS = 0.15, -- 情报足够高时可获得的最大战斗加成
	ARMY_INTEL_COMBAT_BONUS_FACTOR_ATTACK = 1.0, -- 攻击加成的倍率
	ARMY_INTEL_COMBAT_BONUS_FACTOR_DEFENSE = 1.0, -- 防御加成的倍率

	ARMY_INTEL_COMBAT_BONUS_MIN_INTEL_FOR_BONUS = 5, -- 开始获得战斗加成的最低情报值
	ARMY_INTEL_COMBAT_BONUS_MAX_INTEL_FOR_BONUS = 50, -- 完全获得战斗加成的情报值

	NAVAL_SUPREMACY_INTEL_LOW = 0.4, -- 低于此情报值时将受到制海权惩罚
	NAVAL_SUPREMACY_INTEL_LOW_SUPREMACY_PENALTY_START = 0.1, -- 从该情报值开始降低制海权
	NAVAL_SUPREMACY_INTEL_LOW_SUPREMACY_MIN_PENALTY = 0.5, -- 最低制海权惩罚值（线性提升）

	NAVY_FLEET_COUNT_INTEL_MIN = 0.1,
	NAVY_FLEET_COUNT_INTEL_MAX = 0.3,
	NAVY_FLEET_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	NAVY_TASKFORCE_COUNT_INTEL_MIN = 0.3,
	NAVY_TASKFORCE_COUNT_INTEL_MAX = 0.7,
	NAVY_TASKFORCE_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	NAVY_SHIP_COUNT_INTEL_MIN = 0.1,
	NAVY_SHIP_COUNT_INTEL_MAX = 0.8,
	NAVY_SHIP_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	NAVY_MIN_INTEL_TO_SHOW_EXISTING_CATEGORY_TYPES = 0.1, -- 显示舰船分类的最低情报值
	NAVY_SHIP_TYPE_COUNT_INTEL_MIN = 0.3, -- 显示舰船类型数量的最小值
	NAVY_SHIP_TYPE_COUNT_INTEL_MAX = 0.7,
	NAVY_SHIP_TYPE_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	NAVY_MIN_INTEL_TO_SHOW_SHIP_CLASSES = 0.5, -- 解锁显示具体舰船型号
	NAVY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MIN = 0.05,
	NAVY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MAX = 0.7,
	NAVY_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	NAVY_MIN_INTEL_TO_SHOW_SHIP_DESIGN_DETAILS = 0.8,

	AIR_AIRWING_COUNT_INTEL_MIN = 0.0,
	AIR_AIRWING_COUNT_INTEL_MAX = 0.7,
	AIR_AIRWING_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	AIR_MIN_INTEL_TO_SHOW_AIRWING_CLASSES = 0.3,
	AIR_WING_TYPE_COUNT_INTEL_MIN = 0.5,
	AIR_WING_TYPE_COUNT_INTEL_MAX = 0.7,
	AIR_WING_TYPE_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

	AIR_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MIN = 0.1,
	AIR_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_MAX = 0.7,
	AIR_DEPLOYED_MANPOWER_COUNT_RANGE_INTEL_RANGE_AT_LOWEST_INTEL = 0.5,

    RAID_MIN_INTEL_FOR_WARNING_ON_LAUNCH = 0.1, -- 突袭发起时的情报警告阈值
    RAID_MIN_INTEL_FOR_WARNING_HALFWAY_TO_LAUNCH = 0.5, -- 突袭准备一半时的情报警告阈值（仅用于情报界面说明）
    RAID_MIN_INTEL_FOR_WARNING_EARLY_PREPARATION = 0.8, -- 突袭早期准备时的情报警告阈值（同上）

	CIVILIAN_MAPICON_INDUSTRY_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = 0.7,

	MAP_INTEL_VISIBILITY_CUTOFFS = { -- 地图情报可见性阈值，格式为：{阈值, 情报可见性}
		0.1, -50,
		0.4, 0,
		0.6, 50,
		1.0, 100,
	},

	-- 用于部分触发器
	ARMY_AVG_ARMOR_INTEL_MIN = 0.0,
	ARMY_AVG_ARMOR_INTEL_MAX = 0.5,
	ARMY_AVG_ARMOR_RANGE_AT_LOWEST_INTEL = 1.0,

	ARMY_MAX_ARMOR_INTEL_MIN = 0.0,
	ARMY_MAX_ARMOR_INTEL_MAX = 0.5,
	ARMY_MAX_ARMOR_RANGE_AT_LOWEST_INTEL = 1.0,

	ARMY_AVG_PIERCING_INTEL_MIN = 0.0,
	ARMY_AVG_PIERCING_INTEL_MAX = 0.5,
	ARMY_AVG_PIERCING_RANGE_AT_LOWEST_INTEL = 1.0,

	ARMY_MAX_PIERCING_INTEL_MIN = 0.0,
	ARMY_MAX_PIERCING_INTEL_MAX = 0.5,
	ARMY_MAX_PIERCING_RANGE_AT_LOWEST_INTEL = 1.0,

	NAVY_MAPICON_MISSION_COUNT_INTEL_MIN = 0.5, -- 显示海军任务的最低情报值
	NAVY_MAPICON_MISSION_COUNT_INTEL_MAX = 0.8, -- 显示完整海军任务与舰队数量的最低情报值

	NAVY_MAPICON_SHOW_ALL_NAVAL_PORTS = 0.3, -- 显示所有海军港口的最低情报值
	NAVY_MAPICON_NAVAL_PORT_VISIBILITY_DETAIL_THRESHOLDS = { -- 港口提示细节等级
		0.0,	-- 无情报
		0.1,	-- 显示港口等级
		0.3,	-- 模糊舰队数量
		0.7,	-- 完整舰队数量
		0.8,	-- 舰队详情
	},
	NAVY_MAPICON_NAVAL_PORT_TASKFORCE_FUZZY_THRESHOLD = 0.5,

	AIR_MAPICON_MISSION_COUNT_INTEL_MIN = { -- 各类空军任务的最低情报值
		0.3, -- 空中优势
		0.3, -- 近距支援
		0.3, -- 拦截
		0.3, -- 战略轰炸
		0.3, -- 海军轰炸
		0.3, -- 投核弹
		0.3, -- 空降
		0.3, -- 神风特攻
		0.3, -- 港口打击
		0.3, -- 攻击后勤
		0.3, -- 空中补给
		0.3, -- 训练
		0.3, -- 布雷
		0.3, -- 扫雷
		0.3, -- 侦察
		0.3, -- 海上巡逻
	},
	AIR_MAPICON_MISSION_COUNT_INTEL_MAX = {
		0.6, -- 同上，最大情报值
		... -- 同上结构
	},
	AIR_MAPICON_MISSION_COUNT_INTEL_RANGE_AT_LOWEST_INTEL = {
		0.5, -- 同上，最低情报时的模糊范围
		...
	},

	AIR_MAPICON_SHOW_ALL_AIR_PORTS = 0.3, -- 显示所有空军基地的最低情报值
	AIR_MAPICON_AIR_PORT_VISIBILITY_DETAIL_THRESHOLDS = { -- 空军基地提示细节等级
		0.0,	-- 无情报
		0.3,	-- 模糊飞机数量
		0.7,	-- 完整飞机数量
		0.8,	-- 飞机详情
	},
	AIR_MAPICON_AIR_PORT_PLANE_FUZZY_THRESHOLD = 0.5,
	AIR_MIN_INTEL_TO_SHOW_EQUIPMENT_DESIGN_DETAILS = 0.8,
}